language: java

script:
  - cd aula-01/java && mvn clean test checkstyle:check verify -P cobertura spotbugs:check
  - cd ../..
  - cd aula-09/integracao && mvn clean checkstyle:check
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk8