language: java

script:
  - cd aula-01/java && mvn clean test checkstyle:check verify -P cobertura spotbugs:check spotbugs:check -P security
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk8