language: java

script:
  - cd aula-01/java && mvn clean test checkstyle:check verify -P cobertura spotbugs:check
  - cd ../js && npm install && npm run lint && npm run coverage
  - cd ../..
  - cd aula-07/vetor/java && mvn clean checkstyle:check verify -P cobertura
  - cd ../js && npm install && npm run lint && npm run coverage
  - cd ../../..
  - cd aula-08/encontre && mvn clean checkstyle:check
  - cd ../inteiro && mvn clean checkstyle:check
  - cd ../..
  - cd aula-09/integracao && mvn clean checkstyle:check
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
jdk:
  - openjdk8